namespace :import_hmcts do
  task :import_docs, [:csv_path] => :environment do |_, args|
    Import::HmctsImporter.new(ENV["DRY_RUN"]).import(args[:csv_path])
  end

  # Create draft previews of imported editions.
  # Takes a CSV generated by the import_docs task, and the number of seconds to
  # wait between creating each draft. Creating too many at once blocks
  # publishing of new documents because it creates a backlog on the default
  # sidekiq queue.
  task :create_drafts, %i(csv_path pause_seconds) => :environment do |_, args|
    Import::HmctsDraftCreator.new.create_drafts(args[:csv_path], args[:pause_seconds].to_f)
  end
end
