---
glob: "**/*.erb"
exclude:
  - '**/vendor/**/*'
  - 'test/fixtures/**'
  - "app/views/admin/bookmarklets/_find_in_admin.erb"
  - "app/views/admin/bookmarklets/_find_parent_document.erb"
linters:
  Rubocop:
    enabled: true
    exclude:
      - "**/vendor/**/*"
      - "**/vendor/**/.*"
      - "bin/**"
      - "db/**/*"
      - "config/**/*"
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      AllCops:
        DisabledByDefault: true
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
      Rails/SaveBang:
        Enabled: false
