inherit_from:
  - .disabled-rubocop.yml

# Type 'Style' (133):
# Supports --auto-correct
AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  Enabled: false
  EnforcedStyle: indent
  SupportedStyles:
  - outdent
  - indent

# Type 'Rails' (8):
# Supports --auto-correct
ActionFilter:
  Description: Enforces consistent use of action filter methods.
  Enabled: false
  EnforcedStyle: action
  SupportedStyles:
  - action
  - filter
  Include:
  - app/controllers/**/*.rb

# Supports --auto-correct
Alias:
  Description: Use alias_method instead of alias.
  Enabled: false

# Documented
# Supports --auto-correct
AndOr:
  Description: Use &&/|| instead of and/or.
  Enabled: false

AsciiComments:
  Description: Use only ascii symbols in comments.
  Enabled: false

AsciiIdentifiers:
  Description: Use only ascii symbols in identifiers.
  Enabled: false

BlockAlignment:
  Description: Align block ends correctly.
  Enabled: false

# Documented
CaseIndentation:
  Description: Indentation of when in a case/when/[else/]end.
  Enabled: false
  IndentWhenRelativeTo: case
  SupportedStyles:
  - case
  - end
  IndentOneStep: false

ClassAndModuleCamelCase:
  Description: Use CamelCase for classes and modules.
  Enabled: false

ClassAndModuleChildren:
  Description: Checks style of children classes and modules.
  Enabled: false
  EnforcedStyle: nested
  SupportedStyles:
  - nested
  - compact

# Supports --auto-correct
CollectionMethods:
  Description: Preferred collection methods.
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    detect: find
    find_all: select

# Supports --auto-correct
CommentIndentation:
  Description: Indentation of comments.
  Enabled: false

ConstantName:
  Description: Constants should use SCREAMING_SNAKE_CASE.
  Enabled: false

Debugger:
  Description: Check for debugger calls.
  Enabled: true

# Supports --auto-correct
Delegate:
  Description: Prefer delegate method for delegations.
  Enabled: true

# Supports --auto-correct
DefWithParentheses:
  Description: Use def with parentheses when there are arguments.
  Enabled: false

DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  Enabled: true
  EnforcedStyle: leading
  SupportedStyles:
  - leading
  - trailing

EachWithObject:
  Description: Prefer `each_with_object` over `inject` or `reduce`.
  Enabled: false

ElseLayout:
  Description: Check for odd code arrangement in an else block.
  Enabled: false

# Supports --auto-correct
EmptyLineBetweenDefs:
  Description: Use empty lines between defs.
  Enabled: true
  AllowAdjacentOneLineDefs: false

# Supports --auto-correct
EmptyLines:
  Description: Don't use several empty lines in a row.
  Enabled: true

Encoding:
  Description: Use UTF-8 as the source file encoding.
  Enabled: false
  EnforcedStyle: always
  SupportedStyles:
  - when_needed
  - always

EndAlignment:
  Description: Align ends correctly.
  Enabled: false
  AlignWith: keyword
  SupportedStyles:
  - keyword
  - variable

EnsureReturn:
  Description: Never use return in an ensure block.
  Enabled: false

Eval:
  Description: The use of eval represents a serious security risk.
  Enabled: true

FileName:
  Description: Use snake_case for source file names.
  Enabled: false
  Exclude:
  - '**/Rakefile'
  - '**/Gemfile'
  - '**/Capfile'

For:
  Description: Checks use of for or each in multiline loops.
  Enabled: true
  EnforcedStyle: each
  SupportedStyles:
  - for
  - each

# Documented
# Supports --auto-correct
HashSyntax:
  Description: 'Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax { :a => 1,
    :b => 2 }.'
  Enabled: false
  Exclude:
  - 'db/schema.rb'

  EnforcedStyle: ruby19
  SupportedStyles:
  - ruby19
  - hash_rockets

IfUnlessModifier:
  Description: Favor modifier if/unless usage when you have a single-line body.
  Enabled: false
  MaxLineLength: 80

# Documented
# Supports --auto-correct
IndentationWidth:
  Description: Use 2 spaces for indentation.
  Enabled: false

MethodName:
  Description: Use the configured style when naming methods.
  Enabled: false
  EnforcedStyle: snake_case
  SupportedStyles:
  - snake_case
  - camelCase

# Documented
MultilineIfThen:
  Description: Never use then for multi-line if/unless.
  Enabled: false

# Supports --auto-correct
NilComparison:
  Description: Prefer x.nil? to x == nil.
  Enabled: false

# Supports --auto-correct
NonNilCheck:
  Description: Checks for redundant nil checks.
  Enabled: false
  IncludeSemanticChanges: false

# Supports --auto-correct
Not:
  Description: Use ! instead of not.
  Enabled: false

ParenthesesAsGroupedExpression:
  Description: Checks for method calls with a space before the opening parenthesis.
  Enabled: false

# Supports --auto-correct
ParenthesesAroundCondition:
  Description: Don't use parentheses around the condition of an if/unless/while.
  Enabled: false
  AllowSafeAssignment: true

# Supports --auto-correct
RedundantReturn:
  Description: Don't use return where it's not required.
  Enabled: true
  AllowMultipleReturnValues: false

RequireParentheses:
  Description: Use parentheses in the method call to avoid confusion about precedence.
  Enabled: true

SelfAssignment:
  Description: 'Checks for places where self-assignment shorthand should have been used.'
  Enabled: true

# Supports --auto-correct
SingleSpaceBeforeFirstArg:
  Description: Checks that exactly one space is used between a method name and the first
    argument for method calls without parentheses.
  Enabled: false

# Supports --auto-correct
SpaceAfterColon:
  Description: Use spaces after colons.
  Enabled: true

# Supports --auto-correct
SpaceAfterComma:
  Description: Use spaces after commas.
  Enabled: true

# Supports --auto-correct
SpaceAfterControlKeyword:
  Description: Use spaces after if/elsif/unless/while/until/case/when.
  Enabled: true

# Supports --auto-correct
SpaceAfterMethodName:
  Description: Never put a space between a method name and the opening parenthesis in
    a method definition.
  Enabled: true

# Supports --auto-correct
SpaceAfterNot:
  Description: Tracks redundant space after the ! operator.
  Enabled: true

# Supports --auto-correct
SpaceAfterSemicolon:
  Description: Use spaces after semicolons.
  Enabled: true

# Supports --auto-correct
SpaceAroundEqualsInParameterDefault:
  Description: Checks that the equals signs in parameter default assignments have or
    don't have surrounding space depending on configuration.
  Enabled: true
  EnforcedStyle: space
  SupportedStyles:
  - space
  - no_space

# Supports --auto-correct
SpaceAroundOperators:
  Description: Use spaces around operators.
  Enabled: true

# Supports --auto-correct
SpaceBeforeBlockBraces:
  Description: Checks that the left block brace has or doesn't have space before it.
  Enabled: true
  EnforcedStyle: space
  SupportedStyles:
  - space
  - no_space

# Supports --auto-correct
SpaceBeforeModifierKeyword:
  Description: Put a space before the modifier keyword.
  Enabled: true

# Documented
# Supports --auto-correct
SpaceInsideBrackets:
  Description: No spaces after [ or before ].
  Enabled: true

# Supports --auto-correct
SpaceInsideParens:
  Description: No spaces after ( or before ).
  Enabled: true

Tab:
  Description: No hard tabs.
  Enabled: true

# Supports --auto-correct
TrailingBlankLines:
  Description: Checks trailing blank lines and final newline.
  Enabled: true
  EnforcedStyle: final_newline
  SupportedStyles:
  - final_newline
  - final_blank_line

TrailingComma:
  Description: Checks for trailing comma in parameter lists and literals.
  Enabled: false
  EnforcedStyleForMultiline: comma
  SupportedStyles:
  - comma
  - no_comma

# Supports --auto-correct
TrailingWhitespace:
  Description: Avoid trailing whitespace.
  Enabled: true

# Supports --auto-correct
TrivialAccessors:
  Description: Prefer attr_* methods to trivial readers/writers.
  Enabled: false
  ExactNameMatch: false
  AllowPredicates: false
  AllowDSLWriters: false
  Whitelist:
  - to_ary
  - to_a
  - to_c
  - to_enum
  - to_h
  - to_hash
  - to_i
  - to_int
  - to_io
  - to_open
  - to_path
  - to_proc
  - to_r
  - to_regexp
  - to_str
  - to_s
  - to_sym

UnderscorePrefixedVariableName:
  Description: Do not use prefix `_` for a variable that is used.
  Enabled: false

UnreachableCode:
  Description: Unreachable code.
  Enabled: true

# Supports --auto-correct
UnusedBlockArgument:
  Description: Checks for unused block arguments.
  Enabled: true

# Supports --auto-correct
UnusedMethodArgument:
  Description: Checks for unused method arguments.
  Enabled: true

UselessAssignment:
  Description: Checks for useless assignment to a local variable.
  Enabled: true
  Exclude:
    - test/**/**
    - features/step_definitions/**
    - features/support/**

UselessComparison:
  Description: Checks for comparison of something with itself.
  Enabled: true

UselessElseWithoutRescue:
  Description: Checks for useless `else` in `begin..end` without `rescue`.
  Enabled: true

UselessSetterCall:
  Description: Checks for useless setter call to a local variable.
  Enabled: true

# Documented
VariableName:
  Description: Use the configured style when naming variables.
  Enabled: false
  EnforcedStyle: snake_case
  SupportedStyles:
  - snake_case
  - camelCase

# Supports --auto-correct
WordArray:
  Description: Use %w or %W for arrays of words.
  Enabled: true
  MinSize: 0
