inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

# This has special infrastructure for one-time data
# migration tasks, for which it's common to write to
# STDOUT using 'puts'.
Rails/Output:
  Exclude:
    - 'db/data_migration/*.rb'

Rails/LexicallyScopedActionFilter:
  Enabled: false

# This alerts on methods that aren't introduced until rails 6.0
# it should be removed when we upgrade.
Style/HashEachMethods:
  Enabled: false
