require "test_helper"
require "capybara/rails"

class ContentBlockEditionsTest < ActionDispatch::IntegrationTest
  include Capybara::DSL

  setup do
    login_as_admin
  end

  test "#index returns all Content Block Editions" do
    content_block_document = create(:content_block_document, :email_address)
    create(
      :content_block_edition,
      :email_address,
      details: '"email_address":"example@example.com"',
      content_block_document_id: content_block_document.id,
    )
    visit content_object_store.content_object_store_content_block_editions_path
    assert_text '"email_address":"example@example.com"'
  end

  test "#create creates a new content block with params generated by the schema" do
    schema = stub(fields: %w[foo bar], name: "schema")
    document_title = "Some Title"
    block_type = "block_type"
    details = {
      foo: "Foo text",
      bar: "Bar text",
    }

    ContentObjectStore::ContentBlockSchema.expects(:find_by_block_type).with(block_type).returns(schema)
    ContentObjectStore::ContentBlockEdition.expects(:create!).with do |args|
      args.to_h == {
        document_title:,
        block_type:,
        details:,
      }.with_indifferent_access
    end

    post content_object_store.content_object_store_content_block_editions_path, params: {
      something: "else",
      content_object_store_content_block_edition: {
        document_title:,
        block_type:,
        details:,
      },
    }
  end
end
