module Whitehall
  class PublicationFilterOption < FilterOption
    attr_accessor :publication_types

    Consultation        = create!(id: 1, slug: "consultations", label: I18n.t("document_filters.consultation.all"), search_format_types: %w[publicationesque-consultation], publication_types: [], edition_types: %w[Consultation], group_key: I18n.t("document_filters.consultation.label"))
    OpenConsultation    = create!(id: 2, slug: "open-consultations", label: I18n.t("document.type.open_consultation.one").pluralize, search_format_types: %w[consultation-open], publication_types: [], edition_types: %w[Consultation], group_key: I18n.t("document_filters.consultation.label"))
    ClosedConsultation  = create!(id: 3, slug: "closed-consultations", label: I18n.t("document.type.closed_consultation.one").pluralize, search_format_types: %w[consultation-closed consultation-outcome], publication_types: [], edition_types: %w[Consultation], group_key: I18n.t("document_filters.consultation.label"))
    PolicyPaper         = create!(id: 5, slug: "policy-papers", label: I18n.t("document.type.policy_paper.one").pluralize, search_format_types: PublicationType::PolicyPaper.search_format_types, publication_types: [PublicationType::PolicyPaper], group_key: I18n.t("document_filters.policy_and_guidance.label"))
    Guidance            = create!(id: 6, slug: "guidance", label: I18n.t("document.type.guidance.one").pluralize, search_format_types: PublicationType::Guidance.search_format_types, publication_types: [PublicationType::Guidance, PublicationType::StatutoryGuidance], group_key: I18n.t("document_filters.policy_and_guidance.label"))
    ImpactAssessment    = create!(id: 7, slug: "impact-assessments", label: I18n.t("document.type.impact_assessment.one").pluralize, search_format_types: PublicationType::ImpactAssessment.search_format_types, publication_types: [PublicationType::ImpactAssessment], group_key: I18n.t("document_filters.policy_and_guidance.label"))
    IndependentReport   = create!(id: 8, slug: "independent-reports", label: I18n.t("document.type.independent_report.one").pluralize, search_format_types: PublicationType::IndependentReport.search_format_types, publication_types: [PublicationType::IndependentReport], group_key: I18n.t("document_filters.policy_and_guidance.label"))
    Correspondence      = create!(id: 9, slug: "correspondence", label: I18n.t("document.type.correspondence.one").pluralize, search_format_types: PublicationType::Correspondence.search_format_types, publication_types: [PublicationType::Correspondence], group_key: I18n.t("document_filters.policy_and_guidance.label"))
    ResearchAndAnalysis = create!(id: 10, slug: "research-and-analysis", label: I18n.t("document_filters.research_and_analysis.label"), search_format_types: PublicationType::ResearchAndAnalysis.search_format_types, publication_types: [PublicationType::ResearchAndAnalysis], group_key: I18n.t("document_filters.research_and_statistics.label"))
    Statistics          = create!(id: 11, slug: "statistics", label: I18n.t("document.type.statistics.one").pluralize, search_format_types: %w[publicationesque-statistics], publication_types: [PublicationType::OfficialStatistics, PublicationType::NationalStatistics], edition_types: %w[StatisticalDataSet], group_key: I18n.t("document_filters.research_and_statistics.label"))
    CorporateReport     = create!(id: 12, slug: "corporate-reports", label: I18n.t("document.type.corporate_report.one").pluralize, search_format_types: PublicationType::CorporateReport.search_format_types, publication_types: [PublicationType::CorporateReport], group_key: I18n.t("document_filters.corporate.label"))
    TransparencyData    = create!(id: 13, slug: "transparency-data", label: I18n.t("document.type.transparency.one").pluralize, search_format_types: PublicationType::TransparencyData.search_format_types, publication_types: [PublicationType::TransparencyData], group_key: I18n.t("document_filters.corporate.label"))
    FoiRelease          = create!(id: 14, slug: "foi-releases", label: I18n.t("document.type.foi_release.one").pluralize, search_format_types: PublicationType::FoiRelease.search_format_types, publication_types: [PublicationType::FoiRelease], group_key: I18n.t("document_filters.corporate.label"))
    Form                = create!(id: 15, slug: "forms", label: I18n.t("document.type.form.one").pluralize, search_format_types: PublicationType::Form.search_format_types, publication_types: [PublicationType::Form], group_key: I18n.t("document_filters.other.label"))
    Map                 = create!(id: 16, slug: "maps", label: I18n.t("document.type.map.one").pluralize, search_format_types: PublicationType::Map.search_format_types, publication_types: [PublicationType::Map], group_key: I18n.t("document_filters.other.label"))
    InternationalTreaty = create!(id: 17, slug: "international-treaties", label: I18n.t("document.type.international_treaty.one").pluralize, search_format_types: PublicationType::InternationalTreaty.search_format_types, publication_types: [PublicationType::InternationalTreaty], group_key: I18n.t("document_filters.other.label"))
    PromotionalMaterial = create!(id: 18, slug: "promotional-material", label: I18n.t("document.type.promotional.one").pluralize, search_format_types: PublicationType::PromotionalMaterial.search_format_types, publication_types: [PublicationType::PromotionalMaterial], group_key: I18n.t("document_filters.other.label"))
    Notice              = create!(id: 20, slug: "notices", label: I18n.t("document.type.notice.one").pluralize, search_format_types: PublicationType::Notice.search_format_types, publication_types: [PublicationType::Notice], group_key: I18n.t("document_filters.other.label"))
    Decision            = create!(id: 21, slug: "decisions", label: I18n.t("document.type.decision.one").pluralize, search_format_types: PublicationType::Decision.search_format_types, publication_types: [PublicationType::Decision], group_key: I18n.t("document_filters.other.label"))
    Regulation          = create!(id: 22, slug: "regulations", label: I18n.t("document.type.regulation.one").pluralize, search_format_types: PublicationType::Regulation.search_format_types, publication_types: [PublicationType::Regulation], group_key: I18n.t("document_filters.other.label"))
  end
end
