@startuml
node Whitehall {
object "Document:1" as Document_1 {
  latest_edition_id: 3
  live_edition_id: 3
}
together {
object "NewsArticle:1" as NewsArticle_1 {
  state: superseded
  force_published: true
}
Document_1 *-- NewsArticle_1
object "FileAttachment:1" as FileAttachment_1 {
  deleted: false
}
NewsArticle_1 *-- FileAttachment_1
object "Image:2" as Image_2 {
}
NewsArticle_1 *-- Image_2
}
together {
object "NewsArticle:3" as NewsArticle_3 {
  state: published
  force_published: true
}
Document_1 *-- NewsArticle_3
object "FileAttachment:3" as FileAttachment_3 {
  deleted: false
}
NewsArticle_3 *-- FileAttachment_3
object "Image:3" as Image_3 {
}
NewsArticle_3 *-- Image_3
}
object "AttachmentData:1" as AttachmentData_1 {
  present_at_unpublish: false
}
AttachmentData_1 *-u- FileAttachment_1
AttachmentData_1 *-u- FileAttachment_3
object "ImageData:2" as ImageData_2 {
}
ImageData_2 *-u- Image_2
ImageData_2 *-u- Image_3
}
node PublishingApi {
object "Document:4" as pubapi_Document_4 {
}
object "Edition:4" as pubapi_Edition_4 {
  state: superseded
}
pubapi_Document_4 *-- pubapi_Edition_4
object "Edition:6" as pubapi_Edition_6 {
  state: published
}
pubapi_Document_4 *-- pubapi_Edition_6
}
node AssetManager {
together {
object "WhitehallAsset:X164e681f" as am_WhitehallAsset_X164e681f {
  state: uploaded
  draft: false
}
object "WhitehallAsset:X174e681f" as am_WhitehallAsset_X174e681f {
  state: uploaded
  draft: false
}
}
together {
object "WhitehallAsset:X174e6824" as am_WhitehallAsset_X174e6824 {
  state: uploaded
  draft: false
}
object "WhitehallAsset:X174e6825" as am_WhitehallAsset_X174e6825 {
  state: uploaded
  draft: false
}
note right
 also 5 other images not shown
end note
}
}
Document_1 .. pubapi_Document_4
AttachmentData_1 .. am_WhitehallAsset_X164e681f
AttachmentData_1 .. am_WhitehallAsset_X174e681f
ImageData_2 .. am_WhitehallAsset_X174e6824
ImageData_2 .. am_WhitehallAsset_X174e6825
@enduml