require "govuk_app_config/govuk_prometheus_exporter"
require "collectors/scheduled_publishing_overdue_collector"

GovukPrometheusExporter.configure(collectors: [Collectors::ScheduledPublishingOverdueCollector])
