@startuml asset_attachment_upload_flow

title The sequence of uploading a file attachment in Whitehall (AttachmentData)
skinparam BoxPadding 20
skinparam ParticipantPadding 15

box "Whitehall" #f2fef8
actor publisher
participant "Attachments\nController" as Controller
participant AttachmentData
participant "AssetManager\nStorage" as AssetManagerStorage
participant "DraftEdition\nUpdater" as DraftEditionUpdater
participant "ServiceListeners::\nAttachmentUpdater" as slAttachmentUpdater
end box

box Whitehall job (Sidekiq)
participant "AssetManager\nCreateAssetJob" as AssetManagerCreateAssetJob
participant Asset
participant "PublishingApi\nDraftUpdateJob" as PublishingApiDraftUpdateJob
participant "DraftEdition\nUpdater" as bgDraftEditionUpdater
participant "AssetManager\nAttachmentMetadataJob" as AssetManagerAttachmentMetadataJob
participant "AssetManager::\nAttachmentUpdater" as amAttachmentUpdater
end box

box "Asset Manager" #f2f8fe
participant AssetManager
end box

box "Publishing API" #f2f8fe
participant PublishingApi
end box

publisher -> Controller++ : upload an attachment (#create)
Controller -> AttachmentData : Save attachment
AttachmentData -> AssetManagerStorage : Carrierwave invokes store!
AssetManagerStorage --> AssetManagerCreateAssetJob : Enqueue
Controller -> DraftEditionUpdater : perform update_draft
DraftEditionUpdater -> PublishingApi : Update links, content and republish if necessary
Controller -> slAttachmentUpdater : update_attachment_data!
slAttachmentUpdater --> AssetManagerAttachmentMetadataJob: Enqueue
Controller -> publisher-- : Show attachments

AssetManagerCreateAssetJob -[hidden]> AssetManagerCreateAssetJob++
AssetManagerCreateAssetJob -> AssetManager : Upload the file to Asset Manager
AssetManagerCreateAssetJob -> Asset: Save
AssetManagerCreateAssetJob --> PublishingApiDraftUpdateJob : Enqueue
AssetManagerCreateAssetJob --> AssetManagerAttachmentMetadataJob : Enqueue
AssetManagerCreateAssetJob -[hidden]> AssetManagerCreateAssetJob--

PublishingApiDraftUpdateJob -[hidden]> PublishingApiDraftUpdateJob++
PublishingApiDraftUpdateJob -> bgDraftEditionUpdater
bgDraftEditionUpdater -> PublishingApi : Update links, content and republish if necessary
PublishingApiDraftUpdateJob -[hidden]> PublishingApiDraftUpdateJob--

group Happens 2 times because of DraftEditionUpdater
  AssetManagerAttachmentMetadataJob -[hidden]> AssetManagerAttachmentMetadataJob++
  AssetManagerAttachmentMetadataJob -> amAttachmentUpdater : update
  amAttachmentUpdater -> AssetManager: Update metadata of the Asset\n:access_limited\n:draft\n:parent_document_url\n:redirect_url
  AssetManagerAttachmentMetadataJob -[hidden]> AssetManagerAttachmentMetadataJob--
end group

@enduml
