@startuml edition_state_transitions
hide empty description

state AssetManager #a7afff {
    state asset_start <<start>> #a7afff
    state asset_nonexistent #a7afff
    state asset_draft #a7afff
    state asset_published #a7afff
    state asset_deleted #a7afff
}

state Whitehall #a7ffaf {
    [*] --> draft

    'removed: submitted, rejected, scheculed

    draft -l-> deleted: delete

    draft -[norank]-> published: force_publish

    published -u-> draft: unpublish
    published -u-> draft: new edition also unpublishes

    'draft -u-> draft: unpublish

    published --> superseded: supersede

    published --> withdrawn: withdraw
    withdrawn --> withdrawn: withdraw

    withdrawn --> superseded: unwithdraw

    state Attachment {
        [*] --> nonexistentent
    }
}

asset_start --> asset_nonexistent

asset_nonexistent --> asset_draft: asset uploaded

draft -[dashed]> asset_draft: upload
published -[dashed]> asset_published

asset_draft --> asset_published
asset_published --> asset_draft: draft: false\ndraft: true

asset_published --> asset_deleted: deleted_at: <timestamp>
@enduml