@startuml asset_attachment_upload_flow

title The sequence of uploading a file attachment in Whitehall (AttachmentData)
skinparam BoxPadding 20
skinparam ParticipantPadding 15

box "Whitehall" #f2fef8
actor publisher
participant "Attachments\nController" as Controller
participant AttachmentData
participant "AssetManager\nStorage" as AssetManagerStorage
participant "DraftEdition\nUpdater" as DraftEditionUpdater
participant "ServiceListeners::\nAttachmentUpdater" as slAttachmentUpdater
end box

box Whitehall worker (Sidekiq)
participant "AssetManager\nCreateAssetWorker" as AssetManagerCreateAssetWorker
participant Asset
participant "PublishingApi\nDraftUpdateWorker" as PublishingApiDraftUpdateWorker
participant "DraftEdition\nUpdater" as bgDraftEditionUpdater
participant "AssetManager\nAttachmentMetadataWorker" as AssetManagerAttachmentMetadataWorker
participant "AssetManager::\nAttachmentUpdater" as amAttachmentUpdater
end box

box "Asset Manager" #f2f8fe
participant AssetManager
end box

box "Publishing API" #f2f8fe
participant PublishingApi
end box

publisher -> Controller++ : upload an attachment (#create)
Controller -> AttachmentData : Save attachment
AttachmentData -> AssetManagerStorage : Carrierwave invokes store!
AssetManagerStorage --> AssetManagerCreateAssetWorker : Enqueue
Controller -> DraftEditionUpdater : perform update_draft
DraftEditionUpdater -> PublishingApi : Update links, content and republish if necessary
Controller -> slAttachmentUpdater : update_attachment_data!
slAttachmentUpdater --> AssetManagerAttachmentMetadataWorker: Enqueue
Controller -> publisher-- : Show attachments

AssetManagerCreateAssetWorker -[hidden]> AssetManagerCreateAssetWorker++
AssetManagerCreateAssetWorker -> AssetManager : Upload the file to Asset Manager
AssetManagerCreateAssetWorker -> Asset: Save
AssetManagerCreateAssetWorker --> PublishingApiDraftUpdateWorker : Enqueue
AssetManagerCreateAssetWorker --> AssetManagerAttachmentMetadataWorker : Enqueue
AssetManagerCreateAssetWorker -[hidden]> AssetManagerCreateAssetWorker--

PublishingApiDraftUpdateWorker -[hidden]> PublishingApiDraftUpdateWorker++
PublishingApiDraftUpdateWorker -> bgDraftEditionUpdater
bgDraftEditionUpdater -> PublishingApi : Update links, content and republish if necessary
PublishingApiDraftUpdateWorker -[hidden]> PublishingApiDraftUpdateWorker--

group Happens 2 times because of DraftEditionUpdater
  AssetManagerAttachmentMetadataWorker -[hidden]> AssetManagerAttachmentMetadataWorker++
  AssetManagerAttachmentMetadataWorker -> amAttachmentUpdater : update
  amAttachmentUpdater -> AssetManager: Update metadata of the Asset\n:access_limited\n:draft\n:parent_document_url\n:redirect_url
  AssetManagerAttachmentMetadataWorker -[hidden]> AssetManagerAttachmentMetadataWorker--
end group

@enduml
