@startuml asset-featured-image-upload-flow

title The sequence of uploading an image to content types that are immediately republished (FeaturedImageData)
skinparam BoxPadding 20
skinparam ParticipantPadding 10

box "Whitehall" #f2fef8
actor publisher
participant Controller
participant "AssetManager\nCreateAssetJob" as AssetManagerCreateAssetJob
participant Person
participant FeaturedImageData
participant "AssetManager\nStorage" as AssetManagerStorage
end box

box Whitehall-background-jobs
participant "AssetManager\nCreateAssetJob" as AssetManagerCreateAssetJob
participant Asset as bgAsset
participant FeaturedImageData as bgFeaturedImageData
participant Person as bgPerson
end box

box "Asset Manager" #f2f8fe
participant AssetManager
end box

box "Publishing API" #f2f8fe
participant PublishingApi
end box

publisher -> Controller++ : Upload a new image
Controller -> Person : Save
Person -> PublishingApi : Update content, patch links and republish
Person -> FeaturedImageData : Save
FeaturedImageData -> AssetManagerStorage : Carrierwave invokes store!
AssetManagerStorage --> AssetManagerCreateAssetJob : Enqueue 7 times
Controller -> publisher-- : Show person

group 7 times, once per image variant
  activate AssetManagerCreateAssetJob
  AssetManagerCreateAssetJob -> AssetManager : Upload the image version to Asset Manager
  AssetManagerCreateAssetJob -> bgAsset: Save
  AssetManagerCreateAssetJob -> bgFeaturedImageData : Republish
  bgFeaturedImageData -> bgPerson : Republish
  bgPerson -> PublishingApi-- : Update content, patch links and republish
end group

@enduml
