@startuml

skinparam dpi 300
title The sequence of events when a user subscribes to receive email notifications from a Whitehall listing page on GOV.UK

actor user
user -> "listing page" as list
list -> "email_signups_controller" as controller : subscribe to email alerts
controller -> "url_to_subscriber_list_criteria" as criteria : feed url
criteria -> controller : links hash
controller -> "email-alert-api" as emailalertapi : find_or_create with links hash
database "postgres" as emailalertapidb
emailalertapi -> emailalertapidb : find
emailalertapidb -> emailalertapi : subscriber list or nil

group if nil
	participant govdelivery #LightBlue
	emailalertapi -> govdelivery : create new topic
	govdelivery -> emailalertapi : topic id
	emailalertapi -> emailalertapidb : store subscriber list
end

emailalertapi -> controller : topic id
controller -> user : provide signup url
user -> govdelivery : hand off for rest of journey

@enduml
