@startuml

skinparam dpi 300
title The sequence of creating a file attachment in Whitehall
skinparam BoxPadding 20
skinparam ParticipantPadding 10

box "Whitehall" #f2fef8
actor editor
participant AttachmentController
participant Attachment
database mysql
participant AssetManagerStorage
database filesystem
database sidekiq
participant CreateWhitehallAssetWorker
participant AttachmentSetUploadedToWorker
participant AttachmentUpdater
end box

box "Asset Manager" #f2f8fe
participant AssetController
participant Asset
database am_filesystem
database am_sidekiq
participant VirusScanner
participant SaveToCloudStorageWorker
database S3
end box


editor -> AttachmentController : upload an asset
AttachmentController -> Attachment : save
Attachment -> mysql : Store Asset meta information

group carrierwave
    Attachment -> AssetManagerStorage : Trigger carrierwave magic
    AssetManagerStorage -> filesystem : Store temporary file
    AssetManagerStorage -> sidekiq++ : Enqueue CreateWhitehallAssetWorker
end group

AttachmentController -> editor : Redirect to edition/attachments

group sidekiq
    sidekiq -> CreateWhitehallAssetWorker--: trigger worker
    CreateWhitehallAssetWorker -> AssetController : Upload the file to Asset Manager
    CreateWhitehallAssetWorker -> sidekiq++ : Enqueue AttachmentSetUploadedToWorker
    CreateWhitehallAssetWorker -> filesystem : Remove file
end group

group sidekiq
    sidekiq -> AttachmentSetUploadedToWorker--: trigger worker
    AttachmentSetUploadedToWorker -> Attachment : Update the timestamp of when the file was uploaded
    Attachment -> sidekiq++ : Enqueue AttachmentUpdater
end group

group carrierwave
    AssetController -> Asset : Save
    Asset -> am_filesystem : Store temporary file
    Asset -> am_sidekiq++ : Enqueue VirusScanner
end group

group sidekiq
    am_sidekiq -> VirusScanner--: trigger worker
    VirusScanner -> Asset : Update state to be "clean"
    Asset -> am_sidekiq++ : Enqueue SaveToCloudStorageWorker
end group

group sidekiq
    am_sidekiq -> SaveToCloudStorageWorker--: trigger worker
    SaveToCloudStorageWorker -> S3 : Upload to S3
    SaveToCloudStorageWorker -> Asset : Update state to be "uploaded"
    Asset -> am_filesystem : Remove temp file
end group

group sidekiq
    sidekiq -> AttachmentUpdater--: trigger worker
    AttachmentUpdater -> AssetController : update the state of Asset\n:access_limited\n:draft\n:parent_document_url\n:redirect_url\n:replacement_legacy_url_path
    AssetController -> Asset : Save
end group

@enduml
