@startuml
node Whitehall {
object "Document:8" as Document_8 {
  latest_edition_id: 8
  live_edition_id:
}
together {
object "NewsArticle:8" as NewsArticle_8 {
  state: draft
}
Document_8 *-- NewsArticle_8
object "FileAttachment:9" as FileAttachment_9 {
  deleted: false
}
NewsArticle_8 *-- FileAttachment_9
object "Image:5" as Image_5 {
}
NewsArticle_8 *-- Image_5
}
object "AttachmentData:9" as AttachmentData_9 {
}
AttachmentData_9 *-u- FileAttachment_9
object "ImageData:5" as ImageData_5 {
}
ImageData_5 *-u- Image_5
}


node PublishingApi {
object "Document:11" as pubapi_Document_11 {
}
object "Edition:11" as pubapi_Edition_11 {
  state: draft
}
pubapi_Document_11 *-- pubapi_Edition_11
}



node AssetManager {
object "WhitehallAsset:X16c302fe" as am_WhitehallAsset_X16c302fe {
  state: uploaded
  draft: true
}
object "WhitehallAsset:X17c302fe" as am_WhitehallAsset_X17c302fe {
  state: uploaded
  draft: true
}
object "WhitehallAsset:X17c302ff" as am_WhitehallAsset_X17c302ff {
  state: uploaded
  draft: false
}
object "WhitehallAsset:X17c30300" as am_WhitehallAsset_X17c30300 {
  state: uploaded
  draft: false
}
}

Document_8 .. pubapi_Document_11
ImageData_5 .. am_WhitehallAsset_X17c302ff
ImageData_5 .. am_WhitehallAsset_X17c30300
AttachmentData_9 .. am_WhitehallAsset_X16c302fe
AttachmentData_9 .. am_WhitehallAsset_X17c302fe
@enduml
