# Script to compare the candidate slug (as would be generated by set_slug_from_title)
# against the actual slug column for published editions where slug_override is null or blank.
# Since slug_override is absent, edition[:slug] should equal slug_from_title, so this
# effectively checks whether the stored slug matches what set_slug_from_title would produce today.
#
# Run with: rails runner script/compare_published_slugs.rb
# Or paste directly into the rails console.

mismatches = []
errors = []

editions = Edition.withdrawn
                  .where("slug_override IS NULL OR slug_override = ''")

total = editions.count
puts "Checking #{total} published editions with no slug override..."

editions.find_each.with_index do |edition, i|
  print "." if (i % 100).zero?

  begin
    # Mirrors the early exit in set_slug_from_title:
    # Non-English primaries and CIPs return nil from string_for_slug
    string_for_slug = edition.send(:string_for_slug)
    next if string_for_slug.nil?

    # Mirrors the babosa normalisation in set_slug
    default_slug = string_for_slug.to_slug.normalize(to_ascii: true, max_length: 150).to_s

    candidate_slug = if default_slug.blank?
                       # Mirrors the fallback to document_id for unsupported locales
                       edition.document_id.to_s
                     else
                       # Mirrors the duplicate-checking loop in set_slug
                       found_slug = nil
                       attempt = 1
                       loop do
                         slug_attempt = attempt == 1 ? default_slug : "#{default_slug}--#{attempt}"

                         conflicting = Edition.where_base_path_prefix_matches(edition)
                                              .where(slug: slug_attempt)
                                              .where("document_id != ?", edition.document_id)

                         if conflicting.exists?
                           attempt += 1
                         else
                           found_slug = slug_attempt
                           break
                         end
                       end
                       found_slug
                     end

    # Read the raw slug column, bypassing the slug_override reader
    actual_slug = edition[:slug]

    if candidate_slug != actual_slug
      mismatches << {
        id: edition.id,
        type: edition.type,
        title: edition.title,
        actual_slug: actual_slug,
        candidate_slug: candidate_slug,
        slug_from_title: edition[:slug_from_title],
        slug_override: edition[:slug_override],
      }
    end
  rescue => e
    errors << { id: edition.id, error: e.message }
  end
end

puts "\nDone."
puts "Total checked:    #{total}"
puts "Total mismatches: #{mismatches.count}"
puts "Total errors:     #{errors.count}"

if mismatches.any?
  puts "\n--- Mismatches ---"
  mismatches.each do |m|
    puts "Edition #{m[:id]} (#{m[:type]}, #{m[:state]})"
    puts "  Title:           #{m[:title]}"
    puts "  Current slug:    #{m[:actual_slug]}"
    puts "  Candidate slug:  #{m[:candidate_slug]}"
    puts "--------------------------------------------------------------"
  end
end

if errors.any?
  puts "\n--- Errors ---"
  errors.each do |e|
    puts "Edition #{e[:id]}: #{e[:error]}"
  end
end

