#!/usr/bin/env ruby

$LOAD_PATH << File.dirname(__FILE__) + "/../lib"
require File.dirname(__FILE__) + '/../config/environment'
require 'whitehall/abbreviation_extractor'

Edition.published.find_each do |edition|
  entities = Whitehall::AbbreviationExtractor.new(edition).extract
  if entities.any?
    entities.each do |entity|
      puts entity.to_json
    end
  end
end
