#!/bin/sh

set -e

copy_from_db="whitehall_development"
copy_from_user="whitehall"
copy_from_pass="whitehall"
copy_from_host="localhost"
copy_to_db="whitehall_sanitised"
copy_to_user="whitehall"
copy_to_pass="whitehall"
copy_to_host="localhost"
copy_databases="y"

lorem_ipsum_line="Lorem ipsum dolor sit amet, consectetur adipiscing elit"
lorem_ipsum_slug="lorem-ipsum-dolor-sit-amet-elit"
lorem_ipsum_paragraphs="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget metus leo. Integer ac gravida magna. Vestibulum adipiscing pretium vehicula. Praesent ultrices eros a mi elementum id ultrices ligula ornare. Vivamus mollis, odio id luctus scelerisque, dui nunc semper felis, vitae fermentum tortor ante eget erat. Maecenas eleifend elit nec libero porttitor sodales. Quisque vitae augue ut justo vulputate tincidunt at pellentesque tortor.

In bibendum urna sed sem egestas aliquam tempor leo dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rhoncus adipiscing ultrices. Morbi gravida, lacus vitae adipiscing tincidunt, quam tellus consectetur leo, et posuere tortor metus a nulla. Aliquam erat volutpat. In et ante diam. Nulla laoreet ante ut sem egestas sed placerat elit viverra. Duis tempor congue est, rutrum mattis neque aliquam non. Nunc a massa quis nisl blandit elementum a in elit. Pellentesque sollicitudin, magna nec viverra consectetur, risus ante bibendum diam, vel volutpat risus neque sed risus. Nullam leo enim, faucibus eu consequat facilisis, auctor eget velit. In ultricies lectus in velit commodo tempus. Fusce luctus condimentum mi, eleifend auctor libero volutpat sed. Quisque tempor viverra mauris, non blandit ipsum vulputate viverra. In sed enim nibh, eu auctor urna. Suspendisse potenti.

Proin elementum varius quam, eu fermentum nulla vestibulum sed. Integer urna turpis, malesuada sed vehicula vel, vestibulum gravida purus. Vivamus adipiscing ullamcorper bibendum. Nunc pretium condimentum nisi, sit amet blandit augue accumsan in. Ut in erat urna, eget elementum dui. Nam arcu enim, iaculis at interdum at, viverra non massa. Sed nisl massa, pulvinar in blandit nec, pretium eleifend quam. Nullam a nisi dolor, ornare sagittis felis. Aliquam laoreet sodales leo sit amet rutrum.

Fusce dui ante, ornare a interdum vel, posuere non ipsum. Morbi placerat est ac quam ultrices eget feugiat tortor rhoncus. Duis tempor placerat leo sit amet volutpat. Curabitur dignissim pulvinar sem, non auctor dolor mattis sed. In volutpat volutpat massa quis convallis. In in cursus tortor. Pellentesque massa sem, rhoncus a iaculis ac, tincidunt sit amet nibh.

Etiam eu orci sed massa porttitor volutpat. Maecenas euismod lobortis risus sed vehicula. Proin luctus fringilla odio, in ullamcorper eros suscipit ac. Ut consequat vehicula urna nec posuere. Donec vel dapibus massa. Pellentesque consectetur odio a mauris semper bibendum. In vitae sem sollicitudin est egestas gravida id non urna."

access_limited_edition_ids="SELECT id FROM editions WHERE access_limited = 1"
access_limited_document_ids="SELECT document_id FROM editions WHERE access_limited = 1"

usage() {
    echo "usage: $cmd [ops]" >&2
    echo "    [-d|--from-db]    database to copy" >&2
    echo "    [-u|--from-user]  username for copy" >&2
    echo "    [-p|--from-pass]  password to copy" >&2
    echo "    [-h|--from-host]  hostname to copy" >&2
    echo "    [-D|--to-db]      database to create" >&2
    echo "    [-U|--to-user]    username for target" >&2
    echo "    [-P|--to-pass]    password for target" >&2
    echo "    [-H|--to-host]    hostname for target" >&2
    echo "    [-?|--help]       print usage" >&2
    exit 1
}

while test $# -gt 0 ; do
    case "$1" in
        -d|--from-db) shift; copy_from_db="$1" ; shift; continue;;
        -u|--from-user) shift; copy_from_user="$1" ; shift ; continue;;
        -p|--from-pass) shift; copy_from_pass="$1" ; shift ; continue;;
        -h|--from-host) shift; copy_from_host="$1" ; shift ; continue;;
        -D|--to-db) shift; copy_to_db="$1" ; shift ; continue;;
        -U|--to-user) shift; copy_to_user="$1" ; shift ; continue;;
        -P|--to-pass) shift; copy_to_pass="$1" ; shift ; continue;;
        -H|--to-host) shift; copy_to_host="$1" ; shift ; continue;;
        -n|--no-copy) shift; copy_databases=""; continue;;
        -\?|-h|--help) usage ;;
        --) break ;;
        -*) usage ;;
    esac
    break
done

run_mysql_command() {
    echo $1 | mysql -h$copy_to_host -u$copy_to_user -p$copy_to_pass $copy_to_db
}

# Copy the DB to the new database
if [ -n "$copy_databases" ]; then
    echo "Copying databases..."
    mysqldump -h$copy_from_host -u$copy_from_user -p$copy_from_pass $copy_from_db | mysql -h$copy_to_host -u$copy_to_user -p$copy_to_pass $copy_to_db
    echo "Done"
fi

echo "Anonymising latest access limited drafts..."
run_mysql_command "UPDATE edition_translations SET title='${lorem_ipsum_line}', summary='${lorem_ipsum_line}', body='${lorem_ipsum_paragraphs}' WHERE edition_id IN (${access_limited_edition_ids})" 1> /dev/null
echo "Done"

echo "Anonymising slugs for latest access limited drafts..."
run_mysql_command "UPDATE documents SET slug=concat('${lorem_ipsum_slug}-', id) WHERE id IN (${access_limited_document_ids})" 1> /dev/null
echo "Done"

echo "Anonymising email addresses and comments in fact checks..."
run_mysql_command "UPDATE fact_check_requests SET email_address = concat('fact-email-', id, '@example.com'), comments = '', instructions = '', \`key\` = concat('redacted-', id)"
echo "Done"

echo "Anonymising attachment titles for latest access limited drafts..."
run_mysql_command "UPDATE attachments SET title='${lorem_ipsum_line}' WHERE attachable_type = 'Edition' AND attachable_id IN (${access_limited_edition_ids})" 1> /dev/null
echo "Done"

echo "Anonymising html attachment data for latest access limited drafts..."
run_mysql_command "UPDATE attachments SET body='${lorem_ipsum_paragraphs}', slug=concat('${lorem_ipsum_slug}-', id) WHERE attachable_type = 'Edition' AND attachable_id IN (${access_limited_edition_ids})" 1> /dev/null
echo "Done"

echo "Anonymising file names for attachments on latest access limited drafts..."
run_mysql_command "UPDATE attachment_data SET carrierwave_file='redacted.pdf' WHERE id IN (SELECT attachment_data_id FROM attachments WHERE attachments.attachable_type = 'Edition' AND attachments.attachable_id IN (${access_limited_edition_ids}))" 1> /dev/null
echo "Done"

# This table is no longer used but hasn't yet been dropped or purged so still needs to be scrubbed.
echo "Anonymising old supporting pages linked to latest access limited drafts..."
run_mysql_command "UPDATE supporting_pages SET slug=concat('${lorem_ipsum_slug}-', id), title='${lorem_ipsum_line}', body='${lorem_ipsum_paragraphs}' WHERE edition_id IN (${access_limited_edition_ids})" 1> /dev/null
echo "Done"
