@startuml
node Whitehall {
object "Document:7" as Document_7 {
  latest_edition_id: 7
  live_edition_id:
}
together {
object "NewsArticle:7" as NewsArticle_7 {
  state: draft
}
Document_7 *-- NewsArticle_7
object "FileAttachment:8" as FileAttachment_8 {
  deleted: false
}
NewsArticle_7 *-- FileAttachment_8
object "Image:4" as Image_4 {
}
NewsArticle_7 *-- Image_4
}
object "AttachmentData:8" as AttachmentData_8 {
}
AttachmentData_8 *-u- FileAttachment_8
object "ImageData:4" as ImageData_4 {
}
ImageData_4 *-u- Image_4
}


node PublishingApi {
object "Document:10" as pubapi_Document_10 {
}
object "Edition:10" as pubapi_Edition_10 {
  state: draft
}
pubapi_Document_10 *-- pubapi_Edition_10
}

node AssetManager {
object "WhitehallAsset:X16c302fa" as am_WhitehallAsset_X16c302fa {
  state: uploaded
  draft: true
}
object "WhitehallAsset:X17c302f9" as am_WhitehallAsset_X17c302f9 {
  state: uploaded
  draft: true
}

object "WhitehallAsset:X17c302fa" as am_WhitehallAsset_X17c302fa {
  state: uploaded
  draft: false
}
object "WhitehallAsset:X16c302fb" as am_WhitehallAsset_X16c302fb {
  state: uploaded
  draft: false
}
}


Document_7 .. pubapi_Document_10
ImageData_4 .. am_WhitehallAsset_X17c302fa
ImageData_4 .. am_WhitehallAsset_X16c302fb
AttachmentData_8 .. am_WhitehallAsset_X16c302fa
AttachmentData_8 .. am_WhitehallAsset_X17c302f9
@enduml