@startuml
node Whitehall {
object "Document:7" as Document_7 {
  latest_edition_id:
  live_edition_id:
}
}



node PublishingApi {
object "Document:10" as pubapi_Document_10 {
}
}



node AssetManager {
object "WhitehallAsset:X16c302fa" as am_WhitehallAsset_X16c302fa {
  state: uploaded
  draft: true
  deleted_at: 25 May 09:55
}
object "WhitehallAsset:X17c302f9" as am_WhitehallAsset_X17c302f9 {
  state: uploaded
  draft: true
  deleted_at: 25 May 09:55
}
}

node AssetManager {
object "WhitehallAsset:X17c302fa" as am_WhitehallAsset_X17c302fa {
  state: uploaded
  draft: false
  deleted_at:
}
object "WhitehallAsset:X16c302fb" as am_WhitehallAsset_X16c302fb {
  state: uploaded
  draft: false
  deleted_at:
}
}

Document_7 .. pubapi_Document_10
Whitehall .. AssetManager

@enduml