class Edition < ActiveRecord::Base; end
class SpecialistGuide < Edition; end

class FixSpecialistGuidesWithInvalidHeadings < ActiveRecord::Migration
  def up
    SpecialistGuide.find_each do |specialist_guide|
      headers = Govspeak::Document.new(specialist_guide.body).headers
      first_heading = headers.select { |h| (2..3).cover?(h.level) }.first
      if first_heading && first_heading.level == 3
        extra_h2_markdown = "## Heading generated by migration 20120918101920"
        h3_markdown = "### #{first_heading.text}"
        fixed_headings = "\n\n#{extra_h2_markdown}\n\n#{h3_markdown}"
        fixed_body = specialist_guide.body.gsub(%r{###\s*#{first_heading.text}}, fixed_headings)
        specialist_guide.update_column(:body, fixed_body)
        puts "*** Inserted extra h2 in body of specialist guide with edition ID: #{specialist_guide.id}"
      end
    end
  end

  def down
    # Intentionally left blank
  end
end
