@startuml
node Whitehall {
object "Document:1" as Document_1 {
  latest_edition_id: 1
  live_edition_id:
}
together {
object "NewsArticle:1" as NewsArticle_1 {
  state: draft
}
Document_1 *-- NewsArticle_1
}
}
node PublishingApi {
object "Document:4" as pubapi_Document_4 {
}
object "Edition:4" as pubapi_Edition_4 {
}
pubapi_Document_4 *-- pubapi_Edition_4
}
Document_1 .. pubapi_Document_4
@enduml