@startuml
node Whitehall {
object "Document:1" as Document_1 {
  slug: new-news
  document_type: NewsArticle
  content_id: 7e75befe-e47c-4faa-920f-38699bd72b83
  latest_edition_id: 3
  live_edition_id: 1
}
together {
object "NewsArticle:1" as NewsArticle_1 {
  type: NewsArticle
  state: published
  lock_version: 1
  major_change_published_at: 24 May 20:35
  first_published_at: 24 May 20:35
  force_published: true
  external_url:
}
Document_1 *-- NewsArticle_1
object "FileAttachment:1" as FileAttachment_1 {
  type: FileAttachment
  title: Plantuml manual
  attachment_data_id: 1
  content_id: aece8fa8-a958-4e34-83b1-fbe221d04081
  deleted: false
}
NewsArticle_1 *-- FileAttachment_1
object "Image:2" as Image_2 {
  alt_text:
  caption: san gimignano
}
NewsArticle_1 *-- Image_2
}
together {
object "NewsArticle:3" as NewsArticle_3 {
  type: NewsArticle
  state: draft
  lock_version: 2
  major_change_published_at: 24 May 20:35
  first_published_at: 24 May 20:35
  force_published:
  external_url:
}
Document_1 *-- NewsArticle_3
object "FileAttachment:3" as FileAttachment_3 {
  type: FileAttachment
  title: Plantuml manual
  attachment_data_id: 1
  content_id: aece8fa8-a958-4e34-83b1-fbe221d04081
  deleted: false
}
NewsArticle_3 *-- FileAttachment_3
object "Image:3" as Image_3 {
  alt_text:
  caption: san gimignano
}
NewsArticle_3 *-- Image_3
}
object "AttachmentData:1" as AttachmentData_1 {
  carrierwave_file: PlantUML_Language_Reference_Guide_en.pdf
  content_type: application/pdf
  uploaded_to_asset_manager_at: 24 May 16:28
  present_at_unpublish: false
}
AttachmentData_1 *-u- FileAttachment_1
AttachmentData_1 *-u- FileAttachment_3
object "ImageData:2" as ImageData_2 {
  carrierwave_image: sangim_960_640.png
}
ImageData_2 *-u- Image_2
ImageData_2 *-u- Image_3
}
node PublishingApi {
object "Document:4" as pubapi_Document_4 {
  content_id: 7e75befe-e47c-4faa-920f-38699bd72b83
}
object "Edition:4" as pubapi_Edition_4 {
  title: New news
  public_updated_at: 24 May 19:35
  publishing_app: whitehall
  rendering_app: government-frontend
  update_type: major
  phase: live
  document_type: news_story
  schema_name: news_article
  first_published_at: 24 May 19:35
  state: published
  user_facing_versions:
  content_store: live
  published_at: 24 May 19:35
  major_published_at: 24 May 19:35
  publishing_api_first_published_at: 24 May 19:35
}
pubapi_Document_4 *-- pubapi_Edition_4
object "Edition:6" as pubapi_Edition_6 {
  title: New news
  public_updated_at: 24 May 19:35
  publishing_app: whitehall
  rendering_app: government-frontend
  update_type: major
  phase: live
  document_type: news_story
  schema_name: news_article
  first_published_at: 24 May 19:35
  state: draft
  user_facing_versions:
  content_store: draft
  published_at:
  major_published_at:
  publishing_api_first_published_at: 24 May 19:35
}
pubapi_Document_4 *-- pubapi_Edition_6
}
node AssetManager {
together {
object "WhitehallAsset:646e2d14ad6b5b00164e681f" as am_WhitehallAsset_646e2d14ad6b5b00164e681f {
  state: uploaded
  draft: false
  redirect_url:
  content_type:
  deleted_at:
  file: thumbnail_PlantUML_Language_Reference_Guide_en.pdf.png
  legacy_url_path: .../attachment_data/file/1/(filename)
}
object "WhitehallAsset:646e2d15ad6b5b00174e681f" as am_WhitehallAsset_646e2d15ad6b5b00174e681f {
  state: uploaded
  draft: false
  redirect_url:
  content_type:
  deleted_at:
  file: PlantUML_Language_Reference_Guide_en.pdf
  legacy_url_path: .../attachment_data/file/1/(filename)
}
}
together {
object "WhitehallAsset:646e6282ad6b5b00174e6824" as am_WhitehallAsset_646e6282ad6b5b00174e6824 {
  state: uploaded
  draft: false
  redirect_url:
  content_type:
  deleted_at:
  file: sangim_960_640.png
  legacy_url_path: .../image_data/file/2/(filename)
}
object "WhitehallAsset:646e6282ad6b5b00174e6825" as am_WhitehallAsset_646e6282ad6b5b00174e6825 {
  state: uploaded
  draft: false
  redirect_url:
  content_type:
  deleted_at:
  file: s216_sangim_960_640.png
  legacy_url_path: .../image_data/file/2/(filename)
}
note right
 also 5 other images not shown
end note
}
}
Document_1 .. pubapi_Document_4
AttachmentData_1 .. am_WhitehallAsset_646e2d14ad6b5b00164e681f
AttachmentData_1 .. am_WhitehallAsset_646e2d15ad6b5b00174e681f
ImageData_2 .. am_WhitehallAsset_646e6282ad6b5b00174e6824
ImageData_2 .. am_WhitehallAsset_646e6282ad6b5b00174e6825
@enduml