@startuml

skinparam dpi 300
title The sequence of events that cause email notifications to be sent for Whitehall content on GOV.UK

actor editor
editor -> controller : publish
controller -> edition_services : send publish event
edition_services -> publishing_api_worker : enqueue job with edition id
database mysql
participant publishing_api
database rabbitmq
participant "email-alert-service" as emailalertservice
participant "email-alert-api" as emailalertapi
participant notification_worker
database postgres
controller -> editor : render page

group sidekiq
  publishing_api_worker -> mysql : edition id
  mysql -> publishing_api_worker : edition
  publishing_api_worker -> "publishing-api" as publishing_api : publish
  publishing_api -> rabbitmq : publish event
end group

group consumer
  emailalertservice -> rabbitmq : read
  emailalertservice -> emailalertapi : notify with edition
  emailalertapi -> notification_worker : enqueue job
end group

group sidekiq
  notification_worker -> postgres : links hash
  postgres -> notification_worker : govdelivery topics
  notification_worker -> postgres : log notification
  notification_worker -> govdelivery : send email to topics
end group

@enduml
