name: Run Packwerk Check

on:
  workflow_call:

jobs:
  run-packwerk:
    name: Run Packwerk Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        id: setup-mysql
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@main

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - name: Install additional system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ghostscript

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Initialize database
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec rails db:setup

      - name: Run Packwerk Check
        env:
          RAILS_ENV: test
          GOVUK_CONTENT_SCHEMAS_PATH: vendor/publishing-api/content_schemas
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
        run: bundle exec packwerk check